### ISSUE TITLE
Question About Bilinear Interpolator

### ISSUE THREAD

**Issue by kingnobro** [HTDerekLiu/fuzzy-boolean#1]
Hi Derek, thanks for sharing the code.

When reading the code, I have a question about this line: [link](https://github.com/HTDerekLiu/fuzzy-boolean/blob/14b2b1414e0391132196cca380766e19d72631ae/utils/binary_image_to_sdf_interpolator.py#L19). In particular, I don’t understand why there is a `rotate(-90)`. If I remove the rotation operation, the final result will also rotated. Could you explain what parts of the code are affected by removing this rotation? Thanks.

**Comment by HTDerekLiu** [comment]
Hi, that is just because of the ordering in different libraries are different. Some of them use column-major, some of them use row-major. Rotating 90 degrees tries to make them consistent.
